trainer:
  cwd: C:/Users/ASUS/RETRIEVAL # working directory
  seed: 1234 # randomness seed
  cuda: True # use nvidia gpu
  gpu: 0 # id of gpu

  num_epochs: 3
  epoch_patience: 3 # Patience for early stopping
  log_interval: 250 # Print statistics every n samples.
  loss_weights: [1.0, 0.1, 0.1, 0.1]

  load_for_training: False # load pretrained checkpoint for training
  freeze_block: 10

  # is the model in the training_phase?
  training_phase: True

  dataset:
    path: C:/Users/ASUS/RETRIEVAL/fashion200k
    name: Fashion200k
    type: multi_target
    img_size: [224, 224] # image dimension
    augmentation_type:
    train:
      augmentation: True # do augmentation
    val:
      augmentation: False
    test:
      augmentation: False


  dataloader:
    train:
      batch_size: 4 # batch size
      shuffle: True # shuffle samples after every epoch
      num_workers: 4 # number of thread for dataloader
    test:
      batch_size: 4
      shuffle: False
      num_workers: 4


  model:
    optimizer: # optimizer configuration
      type: AdamW # optimizer type
      lr: 5e-4 # learning rate
      weight_decay: 1e-6 # weight decay
    scheduler: # learning rate scheduler
      type: ReduceLRonPlateau # type of scheduler
      scheduler_factor: 0.5 # learning rate change ratio
      scheduler_patience: 0 # patience for some epochs
      scheduler_min_lr: 5e-6 # minimum learning rate value
      scheduler_verbose: True # print if learning rate is changed
